# Generated by Django 3.1.3 on 2020-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('valueId', models.CharField(max_length=30)),
                ('variable', models.CharField(max_length=30)),
                ('variableId', models.CharField(max_length=30)),
            ],
        ),
    ]
